# Generated by Django 5.1.3 on 2025-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Dessert', 'Dessert'), ('Main Course', 'Main Course'), ('Breakfast', 'Breakfast'), ('Vegetarian', 'Vegetarian'), ('Drinks', 'Drinks')], max_length=50),
        ),
    ]
